#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed man zathura xargs awk # Need install this in order to run

# I stole this idea from lukesmith video: https://www.youtube.com/watch?v=8E8sUNHdzG8&list=WL&index=153
man -k . | fzf "Pick manual page to read in pdf" | awk '{print $1}' | xargs -r man -Tpdf | zathura -
