#!/usr/bin/env zsh
# Reference https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html#Prompt-Expansion
local DIR="%~"
local JOB="%(1j.job=%j .)"
local ERRCODE="%(?.. err=%? )"
export PROMPT_ZSH="${JOB}${ERRCODE}${DIR}
%#"
