#!/usr/bin/env zsh
# [[ ! "$FAST_THEME_NAME" == "ayu" ]] && fast-theme /etc/zsh/plugin-configs/ayu-theme.ini &>/dev/null &! # Load syntax theme
[[ ! "$FAST_THEME_NAME" == "clean" ]] && fast-theme clean &>/dev/null &! # Load syntax theme
