#!/usr/bin/env zsh
emulate -L zsh; setopt extendedglob warncreateglobal pipefail nounset errreturn
need_installed swaybg find shuf yad # Check if command is installed || exit
need_normal_user # Only normal user can run || exit

killall -q swaybg || : # Kill old process, if exist
local directory="${1:-$XDG_PICTURES_DIR/Wallpaper}" # If no argument-1 passed, use wallpaper directory from user home
[[ "${1:-}" == "--choose" ]] && wallpaper-handler "$(yad --file --add-preview --large-preview --title='Choose Wallpaper' --file-filter='image | *.png *.jpg *.jpeg')"
# [[ -d "${directory}" ]] && swaybg -m fill -i $(find "${directory}" -maxdepth 1 -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png \) | shuf -n 1) || : # Check if directory variable is a directory && Set random file from directory as wallpaper
[[ -d "${directory}" ]] && awww img $(find "${directory}" -maxdepth 2 -type f \( -iname \*.jpg -o -iname \*.png \) | shuf -n 1) --transition-step 200 --transition-fps 60 --transition-type grow --transition-angle 30 --transition-duration 1 --transition-pos "$(hyprctl cursorpos)" --invert-y || : # Check if directory variable is a directory && Set random file from directory as wallpaper
# [[ -f "${1:-}" ]] && swaybg -m ${2:-fill} -i "${1}" || : # Check if argument-1 is a file && Set argument-1 as a wallpaper
[[ -f "${1:-}" ]] && awww img "${1}" --resize ${2:-crop} --transition-step 200 --transition-fps 60 --transition-type grow --transition-angle 30 --transition-duration 1 --transition-pos "$(hyprctl cursorpos)" --invert-y || :
