#!/usr/bin/env bash

. /usr/local/bin/ctypes.sh # Execute ctypes.sh

current_program_directory=$(dirname $0)
function build { # compile stdin to a DSO
    local temporary_c_file=$(mktemp /tmp/XXXXXXXX.c) # Create variable with temporary file path
    local temporary_so_file=$(mktemp /tmp/XXXXXXXX.so) # Create variable with temporary file path
    
    [[ -f "${1:-}" ]] && cp -f ${1:-} ${temporary_c_file} # Copy argument-1 of this functions to temporary_c_file (if its a file)
    # cc -fPIC -shared ${temporary_c_file} -o ${temporary_so_file} # Create a shared object file

    cc $(pkg-config --cflags --libs ncurses) -fPIC -shared ${temporary_c_file} -o ${temporary_so_file}
    
    rm -f ${temporary_c_file} # Delete temporary_c_file
    echo ${temporary_so_file} # Print out shared object file path
}
so_file=$(build "${current_program_directory}/main.c") # our code
trap "rm -f ${so_file}" EXIT # Delete shared object file when this program done
dlopen "${so_file}" # load the code
dlcall hello_world # print hello world
